export type Programme = {
  name: string;
  section: "A" | "B" | "C" | "D" | "E";
  type: string;
  forWho: string;
  ageElig: string;
  requirements: string;
  funding: string;
  cohort: string;
  focus: string;
  duration: string;
  alumni: string;
  howIn: string;
  contact: string;
  equity: string;
  timing: string;
  url: string;
  caveats: string;
  tags: string[];
};

export const PROGRAMMES: Programme[] = [
  {
    name: "Techstars London",
    section: "A",
    type: "Accelerator",
    forWho: "Early-stage teams, all verticals; international OK",
    ageElig: "None published",
    requirements: "Investment-suitable company; ~13-wk intensive",
    funding: "$220k day-one: $20k for 5% common + $200k uncapped MFN SAFE",
    cohort: "~6–12 historically; London acceptance UNKNOWN",
    focus: "Sector-agnostic",
    duration: "~13 weeks",
    alumni: "Asset Reality, Tova (recent spotlights)",
    howIn: "techstars.com apply portal",
    contact: "Georgie Smithwick (MD); Millen Wolde-Selasse",
    equity: "5% + SAFE; no fee",
    timing: "Spring 2026 ran; next London window UNKNOWN",
    url: "https://www.techstars.com/accelerators/london",
    caveats: "Verify live investment terms",
    tags: ["mvp", "scaleup", "equity"],
  },
  {
    name: "Entrepreneurs First (London FORM/LAUNCH)",
    section: "A",
    type: "Talent investor / pre-accelerator",
    forWho: "Exceptional individuals; pre-idea OK; no co-founder required",
    ageElig: "No hard age limit",
    requirements: "Relocate London for FORM; IC → SF LAUNCH",
    funding: "£6k equity-free Talent Investment; up to $250k ($125k for 8% + optional $125k MFN SAFE)",
    cohort: "Highly selective; rate UNKNOWN",
    focus: "Ambitious software / deep tech talent",
    duration: "12 wks London + 12 wks SF",
    alumni: "Cleo, Tractable, AccuRx; Aztec, Omnea",
    howIn: "apply.joinef.com; Fall 2026 deadline was 4 Aug 2026",
    contact: "joinef.com",
    equity: "8% + optional SAFE if funded",
    timing: "Fall 2026 London (confirm next cycle)",
    url: "https://www.joinef.com/",
    caveats: "Visa advisory only, not sponsorship",
    tags: ["pre-idea", "student", "alumni", "equity"],
  },
  {
    name: "EF XF (Experienced Founders)",
    section: "A",
    type: "Talent investor (experienced)",
    forWho: "7+ years experience; prior founder or key early team",
    ageElig: "Experienced founders",
    requirements: "2 months London then 3 months SF",
    funding: "$250k activation capital week 8; up to $5M follow-on; $600k+ credits claimed",
    cohort: "Selective; UNKNOWN",
    focus: "Second-time / experienced builders",
    duration: "~5 months (2+3)",
    alumni: "EF network",
    howIn: "joinef.com/register-your-interest-xf2",
    contact: "Tom Bryan (Principal) et al.",
    equity: "Terms not restated as standard 8% — confirm offer",
    timing: "Fall 2026; deadline ~31 Jul rolling/unclear",
    url: "https://www.joinef.com/register-your-interest-xf2/",
    caveats: "Do not assume standard FORM £6k/8% terms",
    tags: ["alumni", "equity", "mvp"],
  },
  {
    name: "Antler UK (London residency)",
    section: "A",
    type: "Inception VC / residency",
    forWho: "Solo or early teams at day-zero; must form team (no solo invest)",
    ageElig: "None published; right to work / visa in progress",
    requirements: "Full-time; 4–6 days/wk in person 8 weeks",
    funding: "£210k = £125k for 8.5% + £85k note; £40k fee deducted; ARC follow-on available",
    cohort: "~80–100 residency; <1% accepted (Antler claim)",
    focus: "Industry-agnostic",
    duration: "8-wk residency + 10–12 wks build/raise",
    alumni: "Capsa AI, Diesta, Cloud Cycle, Unravel",
    howIn: "Apply + partner AMAs",
    contact: "Adam French, Hannah Leach, Jed Rose",
    equity: "8.5% + note; £40k fee in package",
    timing: "Prefer next residency 23 Sep 2026 (FAQ Oct 2025 stale)",
    url: "https://www.antler.co/location/uk",
    caveats: "Confirm residency date on antler.co",
    tags: ["pre-idea", "equity"],
  },
  {
    name: "Founders Factory (Aviva / G-Force / Northwestern)",
    section: "A",
    type: "Venture studio + sector accelerators",
    forWho: "Idea→seed; fintech, climate, health, deeptech tracks",
    ageElig: "UNKNOWN",
    requirements: "Track-specific (Aviva: Pre-Seed–Series A)",
    funding: "Aviva: £50k cash + ~$350k perks; G-Force Climate: €250k; Northwestern Health: $150k + ~$300k perks",
    cohort: "UNKNOWN acceptance; 500+ startups platform claim",
    focus: "Fintech, climate, health, deeptech",
    duration: "Typically ~6 months (or 16 wks health)",
    alumni: "Scan.com, Tembo, Storyblok, Peptone, Perlego, Monolith",
    howIn: "foundersfactory.com programme pages",
    contact: "hello@foundersfactory.com; Brent Hoberman et al.",
    equity: "Platform typically 5–7%; Aviva page silent on %",
    timing: "Aviva/G-Force listed open at research; Northwestern window unclear",
    url: "https://foundersfactory.com/",
    caveats: "Equity % not on Aviva page — use 5–7% platform default carefully",
    tags: ["fintech", "climate", "mvp", "equity"],
  },
  {
    name: "Bethnal Green Ventures",
    section: "A",
    type: "Impact VC accelerator",
    forWho: "Early tech-for-good; UK Ltd by shares; right to work UK",
    ageElig: "None stated",
    requirements: "Tech-enabled impact; ~8–10 hrs/wk; prefer full-time",
    funding: "£60k for 7%; follow-on up to ~£1m selected",
    cohort: "10–15 twice/year; ~3–4% acceptance",
    focus: "Tech for good / people & planet",
    duration: "6 wks intensive + 6 wks coaching",
    alumni: "LettUs Grow, RideLogix, Nuw, Earwig",
    howIn: "Online; no warm intro; hello@bethnalgreenventures.com",
    contact: "Paul Miller; Melanie Hayes; Techspace Goswell Rd",
    equity: "7% non-negotiable; no fee",
    timing: "Autumn 2026 apps closed; next notify ~Nov",
    url: "https://bethnalgreenventures.com/apply",
    caveats: "No longer visa endorsing body",
    tags: ["social", "climate", "mvp", "equity"],
  },
  {
    name: "Zinc",
    section: "A",
    type: "Venture builder / pre-seed",
    forWho: "Individuals & teams building health/environment science-for-impact",
    ageElig: "UNKNOWN",
    requirements: "Full-time historically; UK incorporate if invested",
    funding: "Prefer Startup Route up to £300k (£150k + £150k follow-on); older £250k materials exist",
    cohort: "Historically ~50–70/VB; acceptance UNKNOWN",
    focus: "Health + environment science-for-impact",
    duration: "Historically 6–12 months VB",
    alumni: "Vira Health, Assembly, RideTandem, BelleVie",
    howIn: "zinc.vc application / rolling pre-seed",
    contact: "zinc.vc",
    equity: "Investment equity % UNKNOWN publicly",
    timing: "Rolling; confirm 2026 VB dates",
    url: "https://www.zinc.vc/",
    caveats: "Prefer £300k over older £250k pages",
    tags: ["social", "climate", "pre-idea", "equity"],
  },
  {
    name: "Deep Science Ventures",
    section: "A",
    type: "Venture creator / FiR studio",
    forWho: "Scientist-founders for scoped opportunity areas",
    ageElig: "Role-specific",
    requirements: "Apply to open FiR roles; IC for spinout",
    funding: "FiR ~£4,166/mo consultancy; ~£250k pre-seed at IC",
    cohort: "Role-based; UNKNOWN",
    focus: "Deep science / climate / therapeutics",
    duration: "Often multi-month to ~18 months",
    alumni: "Portfolio on deepscienceventures.com",
    howIn: "Open FiR postings",
    contact: "deepscienceventures.com",
    equity: "Founders majority; studio % UNKNOWN fixed",
    timing: "Rolling open roles",
    url: "https://deepscienceventures.com/",
    caveats: "Not a classic open cohort accelerator",
    tags: ["research spinout", "climate", "equity"],
  },
  {
    name: "MassChallenge UK",
    section: "A",
    type: "Zero-equity accelerator + prizes",
    forWho: "Early-stage impactful startups; AI/cyber/foodtech+ tracks",
    ageElig: "None published",
    requirements: "Events in London (+ Switzerland join)",
    funding: "0% equity; compete for non-dilutive prizes (UK+CH prize pool large)",
    cohort: "~67–71 UK companies (2026 reporting conflict — use range)",
    focus: "AI & autonomy, cyber, food/ag, impact",
    duration: "~4 months (e.g. Jun–Oct 2026)",
    alumni: "Global MC network",
    howIn: "Annual applications",
    contact: "David Kinsella (MD UK)",
    equity: "0%",
    timing: "2026 cohort selected; next ~early 2027",
    url: "https://masschallenge.org/programs-united-kingdom/",
    caveats: "Cohort size reported as ~67–71",
    tags: ["mvp", "social", "climate", "non-dilutive"],
  },
  {
    name: "Seedcamp",
    section: "A",
    type: "Seed VC (not fixed accelerator)",
    forWho: "Pre-product to early revenue Europe/Israel",
    ageElig: "N/A",
    requirements: "Pitch Us; no residency",
    funding: "First cheque $350k–$1.25M; $320M = Fund VII $220M + Select $100M",
    cohort: "Continuous; ~100–120 Fund VII first checks targeted",
    focus: "Sector-agnostic tech",
    duration: "Ongoing partnership",
    alumni: "Revolut, Wise, UiPath, Synthesia, Pleo",
    howIn: "seedcamp.com Pitch Us",
    contact: "Reshma Sohoni; Carlos Espinal",
    equity: "Deal-by-deal (~5–10% secondary cite — confirm)",
    timing: "Rolling",
    url: "https://seedcamp.com/",
    caveats: "Do not call Fund VII alone $320M",
    tags: ["mvp", "scaleup", "equity"],
  },
  {
    name: "Wayra UK",
    section: "A",
    type: "Corporate CVC / venture-client",
    forWho: "PMF/growth startups with Telefónica/telco fit",
    ageElig: "UNKNOWN",
    requirements: "Working product preferred; partnership potential",
    funding: "Often cited up to ~£250k — confirm deal-by-deal",
    cohort: "Not fixed cohort",
    focus: "Telco-adjacent AI, cyber, cloud, energy, IoT",
    duration: "Relationship-based",
    alumni: "Historical Wayra UK portfolio; Ori exit 2026 (secondary)",
    howIn: "wayra.uk",
    contact: "Tintagel House, Albert Embankment",
    equity: "Equity investment; terms UNKNOWN standardised",
    timing: "Rolling",
    url: "https://www.wayra.uk",
    caveats: "Verify cheque size on current process",
    tags: ["fintech", "mvp", "scaleup", "equity"],
  },
  {
    name: "FinTech Innovation Lab London (FIL)",
    section: "A",
    type: "Corporate accelerator (Accenture)",
    forWho: "Seed–Series B fintech/insurtech or FS entrants",
    ageElig: "Work-eligible UK; Lab does not sponsor visas",
    requirements: "In-person London commitment; beta+ preferred",
    funding: "None (no equity → no cash)",
    cohort: "FIL26: 14 startups; ~25+ FI partners",
    focus: "Enterprise FS adoption / GenAI / compliance",
    duration: "12 weeks",
    alumni: "Hazy, Akoni, Bud; 230 alumni claim",
    howIn: "Competitive apply → client pitch days",
    contact: "fintechinnovationlab.com",
    equity: "0%; no fee",
    timing: "FIL26 done; FIL27 timing UNKNOWN (stale CTAs)",
    url: "https://fintechinnovationlab.com/regions/london",
    caveats: "Site CTAs stale — confirm next cycle",
    tags: ["fintech", "mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "Lloyd's Lab Accelerator",
    section: "A",
    type: "InsurTech / market-access accelerator",
    forWho: "Global startups–scaleups; insurance experience not required; ≥18",
    ageElig: "≥18",
    requirements: "Apply → Pitch Day; NDA + participation agreement",
    funding: "None stated",
    cohort: "~10–12 of 150–200 apps; ~2 cohorts/year",
    focus: "InsurTech / Lloyd's market access",
    duration: "10 weeks",
    alumni: ">$1.4B raised claim (C17 page)",
    howIn: "lloyds.com Lloyd's Lab apply",
    contact: "lloydslab@lloyds.com",
    equity: "0%; free",
    timing: "C17: start 28 Sep 2026; Demo Day 9 Dec 2026",
    url: "https://www.lloyds.com/insights/lloyds-lab/programmes-and-initiatives/lloyds-lab-accelerator",
    caveats: "Visa own responsibility",
    tags: ["fintech", "mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "CDL-London",
    section: "A",
    type: "Objectives-based mentorship (non-profit)",
    forWho: "Seed science/tech; Minerals & Healthcare Robotics streams; global OK",
    ageElig: "Seed-stage science founders",
    requirements: "Milestone programme; apply portal",
    funding: "No fees, no equity; mentorship + investor access",
    cohort: "Selective; rate UNKNOWN",
    focus: "Minerals / healthcare robotics",
    duration: "~9 months",
    alumni: "CDL global network",
    howIn: "creativedestructionlab.com/london",
    contact: "cdl-london@creativedestructionlab.com; hosted at Imperial",
    equity: "0%",
    timing: "2026/27 apps closed after 24 Jul 2026",
    url: "https://creativedestructionlab.com/locations/london/",
    caveats: "Open globally — not Imperial-students-only",
    tags: ["research spinout", "mvp", "non-dilutive"],
  },
  {
    name: "Creator Fund",
    section: "A",
    type: "Pre-seed deeptech VC + Venture Fellow",
    forWho: "PhD/scientific founders; student fellows",
    ageElig: "Student/PhD-oriented",
    requirements: "Scientific founding potential",
    funding: "Pre-seed cheques UNKNOWN officially; fund ~$56M press",
    cohort: "Fellows ~40/450 press-only UNVERIFIED",
    focus: "University deep tech",
    duration: "Fellowship + rolling invest",
    alumni: "Helical AI, Ovo Labs, BaseImmune, Loci (exit)",
    howIn: "thecreatorfund.com",
    contact: "Jamie Macfarlane",
    equity: "Yes on investment",
    timing: "Rolling + annual fellows",
    url: "https://thecreatorfund.com/",
    caveats: "40/450 fellows is press-only unverified",
    tags: ["student", "research spinout", "equity"],
  },
  {
    name: "Cancer Tech Accelerator",
    section: "A",
    type: "Research commercialisation + grants",
    forWho: "Students, PhDs, postdocs, clinicians, entrepreneurs in oncology tech",
    ageElig: "None",
    requirements: "Cancer-related tech; TTO engagement strongly advised",
    funding: "Phase II grants (non-dilutive); possible £2k/mo stipend; amounts vary",
    cohort: "270+ innovators since 2021",
    focus: "Cancer diagnostics/devices/data",
    duration: "Bootcamp + ~3 mo Phase I + ~4 mo Phase II",
    alumni: "cancertechaccelerator.co.uk portfolio",
    howIn: "Apply online; Capital Enterprise delivery",
    contact: "medtech.ce@capitalenterprise.org",
    equity: "Non-dilutive grants",
    timing: "2026 apps closed Mar; watch 2027",
    url: "https://www.cancertechaccelerator.co.uk/",
    caveats: "Delivered with Capital Enterprise / CRUK et al.",
    tags: ["student", "research spinout", "non-dilutive"],
  },
  {
    name: "Plug and Play UK",
    section: "A",
    type: "Corporate innovation batches",
    forWho: "Sector-fit startups (aviation, health, manufacturing batches)",
    ageElig: "UNKNOWN",
    requirements: "Per open call",
    funding: "Programme equity UNKNOWN; Ventures separate",
    cohort: "Batch-dependent (~10 health historically)",
    focus: "Sector corporate innovation",
    duration: "Often ~12 weeks",
    alumni: "UNKNOWN UK-specific list",
    howIn: "Per-call LinkedIn/partner links",
    contact: "London HQ: 20 Gracechurch St EC3V 0BG",
    equity: "UNKNOWN on UK pages",
    timing: "2026 sector calls (e.g. IAGi closed May)",
    url: "https://www.plugandplaytechcenter.com",
    caveats: "London legal HQ + regional batches — not one campus accelerator",
    tags: ["mvp", "scaleup", "fintech"],
  },
  {
    name: "Plexal / Cyber Runway / Scaleup delivery",
    section: "A",
    type: "Hub + programme delivery (Here East)",
    forWho: "Cyber startups (Cyber Runway); scaleups via Eagle Labs Scaleup",
    ageElig: "Programme-specific",
    requirements: "Cyber Runway / Scaleup criteria",
    funding: "Typically 0% equity; retain IP",
    cohort: "CR5: 48 across tracks; Scaleup: 18 places",
    focus: "Cyber + scaleup delivery",
    duration: "Scaleup ~4 months; Cyber Runway multi-track",
    alumni: "UNKNOWN aggregate",
    howIn: "plexal.com / Eagle Labs Scaleup",
    contact: "cyberrunway@plexal.com",
    equity: "0% typical",
    timing: "Scaleup starts 28 Sep 2026; Cyber Runway next UNKNOWN",
    url: "https://www.plexal.com/",
    caveats: "Plexal delivers; Eagle Labs brands Scaleup",
    tags: ["scaleup", "mvp", "non-dilutive"],
  },
  {
    name: "Digital Catapult (Twin / AI Sprints / Black Founders)",
    section: "A",
    type: "Catapult challenges / sprints / grants",
    forWho: "UK AI/creative/twin tech SMEs; Black founders creative track",
    ageElig: "N/A company stage",
    requirements: "E.g. AI Sprints: TRL 4–5; 3-person team",
    funding: "Twin: up to £100k IUK grant (9 partnerships); others support/state aid",
    cohort: "Twin: 9; Black Founders: up to 15",
    focus: "AI, digital twin, creative deep-tech",
    duration: "Twin 9 months; AI Sprints to Feb 2027; BF 14 weeks",
    alumni: "UNKNOWN",
    howIn: "digicatapult.org.uk opportunities",
    contact: "Digital Catapult apply flows",
    equity: "Typically no equity; grant rules apply",
    timing: "Twin apps to 6 Sep 2026; AI Sprints apps to 16 Aug 2026; BF ended Mar 2026",
    url: "https://www.digicatapult.org.uk/",
    caveats: "Challenge/grant model — not classic equity accelerator",
    tags: ["mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "EarthScale",
    section: "A",
    type: "Climate scale programme (Research England)",
    forWho: "IP-rich / pre–Series A climate ventures; UK-registered",
    ageElig: "TRL/SwRL 5–6; seed raised",
    requirements: "≥2 days/month; commercial readiness",
    funding: "Innovation vouchers / facility access; no headline cash invest",
    cohort: "C1:16; C2:14",
    focus: "Climate manufacturing / Series A readiness",
    duration: "12 months",
    alumni: "UNKNOWN",
    howIn: "earthscale.co.uk; Imperial-led hub among UK unis",
    contact: "earthscale.co.uk",
    equity: "Not stated as equity take",
    timing: "C2 Jun 2026–Jun 2027; C3 apps late 2026",
    url: "https://earthscale.co.uk",
    caveats: "UK-wide; Imperial is a regional hub",
    tags: ["climate", "scaleup", "research spinout", "non-dilutive"],
  },
  {
    name: "Tech Nation DeepTech + Upscale (Founders Forum)",
    section: "A",
    type: "Founder network programmes (private TN)",
    forWho: "DeepTech: post-spinout→Series A; Upscale: £5m+ raised or £1m+ revenue; UK HQ",
    ageElig: "Company stage gates",
    requirements: "UK HQ; London in-person sessions (Upscale)",
    funding: "Support only; free / no equity",
    cohort: "DeepTech 10–15 twice/year",
    focus: "Deeptech growth; scaleup network",
    duration: "DeepTech 6 months; Upscale Sep–Dec 2026",
    alumni: "UNKNOWN list here",
    howIn: "technation.io programmes",
    contact: "technation.io",
    equity: "0%",
    timing: "DeepTech apps 10 Jun–31 Jul 2026; Upscale apps 2 Jul–23 Aug 2026",
    url: "https://technation.io/programmes/deeptech/",
    caveats: "Gov TN ended ~Mar 2023; private Founders Forum TN still active 2026 — NOT dead",
    tags: ["scaleup", "research spinout", "non-dilutive"],
  },
  {
    name: "Founder Institute London",
    section: "A",
    type: "Pre-seed company builder",
    forWho: "Idea/pre-seed founders; pre-incorporation OK",
    ageElig: "UNKNOWN",
    requirements: "Curriculum + mentor sessions",
    funding: "No cash",
    cohort: "Chapter-based; UNKNOWN",
    focus: "Idea → company formation",
    duration: "25 Nov 2026 – 28 Jan 2027",
    alumni: "Global FI (Udemy etc.); London list UNKNOWN",
    howIn: "fi.co/london",
    contact: "FI London chapter",
    equity: "2.5% warrant (Equity Collective) + fee $999 early / higher after",
    timing: "Early deadline 8 Sep 2026; early fee $999",
    url: "https://fi.co/london",
    caveats: "Confirm right-to-work for London ops",
    tags: ["pre-idea", "student", "alumni", "equity"],
  },
  {
    name: "Level39",
    section: "A",
    type: "Innovation hub / membership (not equity accel)",
    forWho: "Fintech, cyber, AI, healthtech scaleups",
    ageElig: "Membership screening",
    requirements: "Paid membership / trial",
    funding: "No programme cheque",
    cohort: "180+ member businesses",
    focus: "Fintech/cyber/AI scale network",
    duration: "Ongoing",
    alumni: "Early Revolut/Onfido association (historical)",
    howIn: "Trial day → membership",
    contact: "members@level39.co",
    equity: "0% (membership fees: Community from £300+VAT/mo)",
    timing: "Rolling",
    url: "https://level39.co/",
    caveats: "Hub + hosted TEA for Norwegian scaleups — not own open accelerator",
    tags: ["fintech", "scaleup"],
  },
  {
    name: "Barclays Eagle Labs (London)",
    section: "B",
    type: "Bank hub + equity-free programmes",
    forWho: "Tech/innovation startups & scaleups",
    ageElig: "Programme-specific",
    requirements: "Vary (Scaleup: £2M+ raised/revenue, ≥10 staff)",
    funding: "Programmes free; no programme cheque; desks paid",
    cohort: "Scaleup: 18; Sales Growth capped 15",
    focus: "AI, fintech, climate, general tech",
    duration: "Scaleup ~4 mo; Funding Readiness 10 wks",
    alumni: "13,000+ businesses supported since 2015 (org)",
    howIn: "labs.uk.barclays programme pages",
    contact: "Shoreditch Innovation Hub, 41 Luke Street EC2A 4DP",
    equity: "Programmes 0%; hub desks paid (Club/Resident)",
    timing: "Funding Readiness apps 24 Jul–31 Aug 2026; Scaleup starts 28 Sep 2026",
    url: "https://labs.uk.barclays/",
    caveats: "Canonical Eagle Labs entry — programmes listed once under CE delivery too",
    tags: ["mvp", "scaleup", "non-dilutive", "fintech"],
  },
  {
    name: "NatWest Accelerator",
    section: "B",
    type: "Always-on entrepreneur community + hubs",
    forWho: "UK businesses with growth ambitions; soft open",
    ageElig: "Broad",
    requirements: "App download; hubs optional",
    funding: "Pitch competitions with prize pots (£1m series announced 2025+)",
    cohort: "Community >10,000 by end-2025; not selective",
    focus: "Community, funding readiness, growth",
    duration: "Ongoing",
    alumni: "Broad SME base",
    howIn: "NatWest Accelerator app",
    contact: "London hub (~Feb 2026) + UK hubs",
    equity: "Widely reported 0% equity — soft claim (not hard-stated on product page)",
    timing: "Always open",
    url: "https://www.natwest.com/business/business-services/entrepreneur-accelerator.html",
    caveats: "Soft claim on 0% equity",
    tags: ["mvp", "scaleup", "pre-idea", "non-dilutive"],
  },
  {
    name: "Google for Startups Accelerator (UK)",
    section: "B",
    type: "Equity-free corporate accelerator",
    forWho: "Seed–Series A UK AI-first / thematic tracks",
    ageElig: "Stage gates on some tracks",
    requirements: "AI/tech central; CEO/CTO engagement",
    funding: "0% equity; Google Cloud credits (eligibility-based)",
    cohort: "Typically 10–15",
    focus: "AI, climate, energy tracks",
    duration: "~10–12 weeks hybrid",
    alumni: "2025 AI First UK graduated Jul 2025",
    howIn: "startup.google.com when windows open",
    contact: "Google for Startups Europe/UK team",
    equity: "0%",
    timing: "Periodic calls; monitor pages",
    url: "https://startup.google.com/programs/accelerator/ai-first/united-kingdom/",
    caveats: "No Campus London building — Campus dead 2021",
    tags: ["mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "NCTA (Sustainable Ventures × Eagle Labs)",
    section: "B",
    type: "Equity-free climate accelerator + competition",
    forWho: "UK-incorporated climate-tech SMEs",
    ageElig: "UK incorporation; climate core",
    requirements: "Express interest; Tiers 2–3 need Barclays customer status",
    funding: "Up to $200k Google Cloud credits (official NCTA page)",
    cohort: "Broad Tier 1; rates UNKNOWN",
    focus: "Climate tech",
    duration: "Virtual; next starts Oct 2026",
    alumni: "SV claims 1000+ startups supported historically",
    howIn: "sustainableventures.co.uk/ncta",
    contact: "Sustainable Ventures + Eagle Labs",
    equity: "0%",
    timing: "Programme starting October 2026",
    url: "https://www.sustainableventures.co.uk/ncta",
    caveats: "Use $200k official — not $250k press",
    tags: ["climate", "mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "Microsoft / AWS founder programmes (notes)",
    section: "B",
    type: "Cloud credits / founder hubs (not London incubators)",
    forWho: "Startups meeting cloud programme criteria",
    ageElig: "N/A",
    requirements: "Apply via Microsoft for Startups / AWS Activate",
    funding: "Credits packages (amounts vary; confirm current)",
    cohort: "N/A open programmes",
    focus: "Cloud infra support",
    duration: "Credit windows",
    alumni: "N/A",
    howIn: "Microsoft for Startups; AWS Activate",
    contact: "Vendor founder portals",
    equity: "0%",
    timing: "Rolling",
    url: "https://www.microsoft.com/en-us/startups",
    caveats: "Not London-specific incubators — stack with local programmes",
    tags: ["mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "UCL Hatchery",
    section: "C",
    type: "Equity-free incubator",
    forWho: "Current UCL students; alumni ≤2 years",
    ageElig: "UCL affiliation window",
    requirements: "Companies House before apply; induction attendance",
    funding: "No direct grant; funded interns opportunity; free desks (≤4)",
    cohort: "Competitive; 2 intakes/year; size UNKNOWN",
    focus: "Sector-agnostic",
    duration: "2 years (+ 8-wk induction)",
    alumni: "Stasher; Your Juno; Oxford Heartbeat; Humanloop→YC",
    howIn: "Info session → form → interview",
    contact: "entrepreneurship@ucl.ac.uk",
    equity: "0%; free",
    timing: "Autumn 2026 apps 1 Jun–30 Aug; interviews 16–17 Sep; induction from 15 Oct",
    url: "https://www.ucl.ac.uk/enterprise/students/grow-your-startup-hatchery-incubator-programme",
    caveats: "Free selective incubator inside BaseKX",
    tags: ["student", "alumni", "mvp", "non-dilutive"],
  },
  {
    name: "UCL Venture Builder",
    section: "C",
    type: "Pre-incubator",
    forWho: "Students, staff, recent grads (typically ≤2 years)",
    ageElig: "UCL community",
    requirements: "Tested idea stage",
    funding: "Share of prize pot — official £4k; some intakes higher (cohort-variable)",
    cohort: "UNKNOWN",
    focus: "Idea validation",
    duration: "10 weeks hybrid",
    alumni: "Pathway into Hatchery",
    howIn: "UCL Enterprise apply",
    contact: "entrepreneurship@ucl.ac.uk",
    equity: "0%",
    timing: "e.g. spring intakes — confirm page",
    url: "https://www.ucl.ac.uk/enterprise/students/launch-your-entrepreneurial-venture/venture-builder-turn-your-idea-reality",
    caveats: "Prize cohort-variable (£4k official; some higher)",
    tags: ["student", "alumni", "pre-idea", "non-dilutive"],
  },
  {
    name: "UCL BaseKX",
    section: "C",
    type: "Paid entrepreneurship hub",
    forWho: "UCL community + members seeking coworking/events",
    ageElig: "Membership rules",
    requirements: "Hub membership (paid)",
    funding: "None as hub membership",
    cohort: "N/A hub",
    focus: "Workshops, advisors, community at King's Cross",
    duration: "Membership",
    alumni: "Houses Hatchery companies",
    howIn: "UCL Enterprise BaseKX access pages",
    contact: "entrepreneurship@ucl.ac.uk",
    equity: "0% (paid desks/membership)",
    timing: "Ongoing",
    url: "https://www.ucl.ac.uk/enterprise/businesses/access-coworking-space-your-startup-or-business",
    caveats: "BaseKX = paid hub; Hatchery = free selective incubator inside it — do not conflate",
    tags: ["student", "alumni", "mvp"],
  },
  {
    name: "UCLB Portico Ventures",
    section: "C",
    type: "TTO / spinout pathway",
    forWho: "Academic founders; non-patentable IP pathway",
    ageElig: "Research IP",
    requirements: "UCLB commercialisation process",
    funding: "UCL Technology Fund; UCLB seed up to £250k; PoC",
    cohort: "Deal-by-deal",
    focus: "Research commercialisation",
    duration: "Deal-dependent",
    alumni: "UCL spinout portfolio",
    howIn: "Via UCLB",
    contact: "uclb.com",
    equity: "Portico: 10% first-time pathway OR 5% experienced founder-driven",
    timing: "Rolling",
    url: "https://www.uclb.com/",
    caveats: "Do not quote single flat equity %",
    tags: ["research spinout", "equity"],
  },
  {
    name: "Imperial VCC",
    section: "C",
    type: "Competition + accelerator-style programme",
    forWho: "Imperial students/ECRs/alumni ≤3 years; external teammates OK",
    ageElig: "≤3y alumni",
    requirements: "Market research; ineligible if >£100k non-grant funding raised",
    funding: "£100k prize fund equity-free",
    cohort: "25 teams / 5 tracks",
    focus: "Multi-track venture competition",
    duration: "~3 months (Aug–Nov 2026)",
    alumni: "Notpla, Recycleye, Shellworks, Monolith.ai",
    howIn: "imperialenterpriselab.com/vcc",
    contact: "vcc@imperial.ac.uk; enterprise.lab@imperial.ac.uk",
    equity: "0%",
    timing: "Apps 27 Apr–14 Jun 2026; start 13 Aug; final 4 Nov 2026",
    url: "https://www.imperialenterpriselab.com/programmes/vcc/",
    caveats: "",
    tags: ["student", "alumni", "pre-idea", "mvp", "non-dilutive"],
  },
  {
    name: "Imperial WE Innovate",
    section: "C",
    type: "Women-led programme + pitch competition",
    forWho: "Women-led Imperial-linked teams; alumni ≤2 years",
    ageElig: "Alumni ≤2 years (not 3)",
    requirements: "Women-led; Imperial link per T&Cs",
    funding: "£30k equity-free prize fund",
    cohort: "~25 Phase 1 → 10 Phase 2 → 5 Final",
    focus: "Women founders",
    duration: "6 months (Jan–Jun)",
    alumni: "600+ women founders; £88m+ raised claim",
    howIn: "imperialenterpriselab.com/we-innovate",
    contact: "enterprise.lab@imperial.ac.uk",
    equity: "0%",
    timing: "Annual Jan–Jun cycle",
    url: "https://www.imperialenterpriselab.com/programmes/we-innovate/",
    caveats: "Alumni window ≤2 years — not 3",
    tags: ["student", "alumni", "pre-idea", "mvp", "non-dilutive"],
  },
  {
    name: "Imperial Incubator (White City)",
    section: "C",
    type: "Wet-lab + office incubator",
    forWho: "Early science startups — Imperial connection NOT required",
    ageElig: "N/A",
    requirements: "Fit to wet-lab/office; licence agreement",
    funding: "No incubator equity investment; helps access grants/investors",
    cohort: "Space-limited",
    focus: "Medtech, biotech, climate, materials",
    duration: "Typically 12–36 months",
    alumni: "Multus and others",
    howIn: "imperialincubator.com",
    contact: "Imperial Incubator",
    equity: "Incubator takes none; spinouts via Founders Choice separately",
    timing: "Rolling applications",
    url: "https://imperialincubator.com/",
    caveats: "Monthly licence fee UNKNOWN publicly",
    tags: ["research spinout", "climate", "mvp"],
  },
  {
    name: "Undaunted Greenhouse",
    section: "C",
    type: "Climate deep-tech accelerator",
    forWho: "Pre-seed climate tech; UK HQ or willing; ≥1 FTE; TRL ~3–5",
    ageElig: "N/A",
    requirements: "Attend Imperial/West London sessions",
    funding: "Up to £20k equity-free grant",
    cohort: "180 startups historically through Undaunted accelerators",
    focus: "Climate tech",
    duration: "12 months",
    alumni: "Undaunted portfolio",
    howIn: "undaunted-hq.org",
    contact: "Undaunted / Imperial",
    equity: "0% (grant-funded model)",
    timing: "Confirm current cohort window",
    url: "https://undaunted-hq.org/programmes/the-greenhouse/",
    caveats: "Canonical Undaunted entry; Imperial + RI partnership",
    tags: ["climate", "research spinout", "mvp", "non-dilutive"],
  },
  {
    name: "Imperial IVM / ICEF / Founders Choice",
    section: "C",
    type: "Mentoring / funds / spinout equity policy",
    forWho: "Imperial students/alumni ≤3y/staff (IVM); Imperial-connected (ICEF); academic spinouts (FC)",
    ageElig: "Programme-specific",
    requirements: "IVM: prior Idea Surgery/coaching",
    funding: "ICEF deal-by-deal equity; IVM mentoring only",
    cohort: "N/A",
    focus: "Long-term mentoring; early equity; founder-friendly spinout equity",
    duration: "IVM long-term; ICEF deal-based",
    alumni: "Imperial spinout ecosystem",
    howIn: "Enterprise Lab / spinout team",
    contact: "enterprise.lab@imperial.ac.uk",
    equity: "Founders Choice: founders can retain up to ~95% (founder-driven route)",
    timing: "Rolling / process-based",
    url: "https://www.imperialenterpriselab.com/",
    caveats: "Three related Imperial pathways grouped",
    tags: ["student", "alumni", "research spinout", "equity", "non-dilutive"],
  },
  {
    name: "Imperial Techcelerate",
    section: "C",
    type: "Customer discovery pre-accelerator (historical)",
    forWho: "Imperial researchers / ECRs (historical)",
    ageElig: "Researcher-focused",
    requirements: "Commercialisation potential; customer interviews",
    funding: "Historical up to ~£30k salary+customer-dev — current UNKNOWN",
    cohort: "54 ECRs since 2018 claim — current UNKNOWN",
    focus: "Deep-tech market validation",
    duration: "Historically ~3 months",
    alumni: "Imperial ECR alumni",
    howIn: "Confirm with Enterprise Lab — not on main 2026 programmes list",
    contact: "enterprise.lab@imperial.ac.uk",
    equity: "UNKNOWN / historically support",
    timing: "Current recruitment UNKNOWN",
    url: "https://www.imperialenterpriselab.com/programmes/techcelerate/",
    caveats: "Historically real; current recruitment UNKNOWN — do not assume open 2026 cohort",
    tags: ["research spinout"],
  },
  {
    name: "Imperial AI SuperConnector",
    section: "C",
    type: "Completed SuperConnector programme",
    forWho: "Was AI commercialisation cohort (completed)",
    ageElig: "N/A",
    requirements: "N/A — not recruiting",
    funding: "Completed programme",
    cohort: "Completed",
    focus: "AI",
    duration: "Completed",
    alumni: "Programme alumni",
    howIn: "Do not apply — completed",
    contact: "N/A",
    equity: "N/A",
    timing: "Completed Jul 2025; not recruiting",
    url: "https://www.imperialenterpriselab.com/programmes/",
    caveats: "CLOSED — completed Jul 2025",
    tags: ["research spinout"],
  },
  {
    name: "King's Start-up Accelerator",
    section: "C",
    type: "Accelerator (ex-King's20)",
    forWho: "King's students & alumni; ≥1 founder King's-affiliated; founder-owned IP",
    ageElig: "King's affiliation",
    requirements: "Validated problem/solution; some traction; full commitment",
    funding: "Grant opportunities / benefits package worth £65k — NOT guaranteed cash; AWS credits; intros",
    cohort: "Cohort X: 17; historically ~17–20",
    focus: "Student/alumni startups",
    duration: "~9–12 months (6 months workshops/sprints + 3 months follow-on)",
    alumni: "C the Signs; Obrizum; SOJO; Veed.io; Gamely",
    howIn: "kcl.ac.uk entrepreneurship apply",
    contact: "Holly Knower; ei@kcl.ac.uk",
    equity: "Founders Pledge: 3% to King's only if £1m raise and/or £1m revenue within 5 years; else 0%",
    timing: "Typically start mid-Jun (2026: 17 Jun–Mar/May 2027)",
    url: "https://www.kcl.ac.uk/entrepreneurship/scale-your-venture/start-ups",
    caveats: "£65k = opportunities/benefits not guaranteed cash; 6+3 structure",
    tags: ["student", "alumni", "mvp", "equity", "non-dilutive"],
  },
  {
    name: "King's Spinout Accelerator",
    section: "C",
    type: "Research spinout accelerator",
    forWho: "King's research staff; university IP; Innovation Disclosure filed",
    ageElig: "Research staff",
    requirements: "PoC+; IP via King's",
    funding: "Support package; space up to 5 desks Bush House",
    cohort: "UNKNOWN",
    focus: "Research spinouts",
    duration: "12 months (Jun 2026–Jun 2027)",
    alumni: "Spinouts raised ~£50m via EI claim",
    howIn: "Apps 2 Feb–8 Mar 2026 cycle",
    contact: "holly.knower@kcl.ac.uk; ei@kcl.ac.uk",
    equity: "Per King's IP Code (distinct from Start-up pledge)",
    timing: "Starts 4 Jun 2026",
    url: "https://www.kcl.ac.uk/entrepreneurship/scale-your-venture/spinouts",
    caveats: "",
    tags: ["research spinout", "equity"],
  },
  {
    name: "King's MedTech Accelerator (LIHE)",
    section: "C",
    type: "MedTech accelerator",
    forWho: "King's researchers/staff; medical devices/healthcare tech",
    ageElig: "King's research community",
    requirements: "MedTech focus; LIHE-run",
    funding: "UNKNOWN prize/equity on thin public pages",
    cohort: "2026 cohort announced",
    focus: "MedTech",
    duration: "6 months part-time",
    alumni: "UNKNOWN",
    howIn: "kcl.ac.uk / LIHE",
    contact: "LIHE / King's EI",
    equity: "UNKNOWN",
    timing: "Confirm current cycle",
    url: "https://www.kcl.ac.uk/bmeis/medtech-accelerator",
    caveats: "Canonical LIHE/MedTech uni entry; thin public terms",
    tags: ["research spinout", "mvp"],
  },
  {
    name: "LSE Generate Fellowship",
    section: "C",
    type: "Year-round fellowship (replaced GAP 2026)",
    forWho: "≥1 co-founder LSE student/alumni/staff; global hybrid OK",
    ageElig: "LSE affiliation",
    requirements: "Commercial venture (not charity-only)",
    funding: "Cash prizes £500–£3,000 via Startup Competitions",
    cohort: "Up to 48/year",
    focus: "Ideation + acceleration; SDG encouraged",
    duration: "3–12 months mentoring",
    alumni: "Generate community",
    howIn: "Apply every 3 months; generate@lse.ac.uk",
    contact: "LJ Silverman; generate@lse.ac.uk",
    equity: "Equity-free (implied)",
    timing: "4 windows/year",
    url: "https://info.lse.ac.uk/staff/divisions/research-and-innovation/generate/fellowship",
    caveats: "GAP (2020–2025) defunct — use Fellowship",
    tags: ["student", "alumni", "pre-idea", "mvp", "social", "non-dilutive"],
  },
  {
    name: "QMUL QIncubator",
    section: "C",
    type: "2-phase incubator",
    forWho: "Current UG/PG students OR alumni ≤3 years; UK-based for programme",
    ageElig: "Current students OR alumni ≤3y",
    requirements: "Team ≤5; lead owns ≥25%",
    funding: "Pitch for share of up to £20,000",
    cohort: "UNKNOWN exact",
    focus: "SDG-aligned encouraged",
    duration: "Phase 1 Jan–Mar + Phase 2 Apr–May 2026 example",
    alumni: "QUEST ecosystem",
    howIn: "quest@qmul.ac.uk",
    contact: "quest@qmul.ac.uk",
    equity: "No equity stated (likely none)",
    timing: "Pitch night 9 Jun 2026 (2026 cycle)",
    url: "https://www.qmul.ac.uk/quest/programmes-and-events/qincubator/",
    caveats: "Students OR alumni ≤3y — not alumni-only",
    tags: ["student", "alumni", "pre-idea", "mvp", "non-dilutive"],
  },
  {
    name: "QMB / QME (Queen Mary)",
    section: "C",
    type: "Physical life sciences / digital health space",
    forWho: "Life sciences & digital health startups (tenants can be external)",
    ageElig: "N/A",
    requirements: "Commercial tenancy fit",
    funding: "None as space product",
    cohort: "N/A",
    focus: "Wet lab / MedTech / AI health",
    duration: "Tenancy",
    alumni: "Whitechapel cluster",
    howIn: "qmbioenterprises.com",
    contact: "QMB Innovation Centre",
    equity: "Commercial rent; 0% programme equity",
    timing: "Rolling",
    url: "https://www.qmbioenterprises.com/",
    caveats: "",
    tags: ["research spinout", "mvp"],
  },
  {
    name: "City Launch Lab / Bayes Entrepreneurship Fund",
    section: "C",
    type: "Accelerator/incubator + VC fund",
    forWho: "Launch Lab: City St George's students/grads; Bayes Fund: UK HQ not Bayes-only",
    ageElig: "Uni for Launch Lab",
    requirements: "Launch Lab: traction; Fund: typically £100k+ revenue",
    funding: "Fund cheques £350k–£1.5m; Launch Lab support",
    cohort: "Launch Lab ~10 per Feb & Oct intake",
    focus: "Student startups + early revenue VC",
    duration: "Launch Lab 3 mo accel + up to 12 mo membership",
    alumni: "CityVentures ecosystem",
    howIn: "launchlab@city.ac.uk; bayesentrepreneurship.fund",
    contact: "pcce@citystgeorges.ac.uk",
    equity: "Fund: yes; Launch Lab: support (no equity stated)",
    timing: "Launch Lab Feb & Oct",
    url: "https://www.citystgeorges.ac.uk/business/start/launch/launch-lab",
    caveats: "Grouped City + Bayes; fund is commercial equity",
    tags: ["student", "alumni", "mvp", "scaleup", "equity", "non-dilutive"],
  },
  {
    name: "UAL CBA / Greenhouse / Launch",
    section: "C",
    type: "Creative graduate programmes",
    forWho: "UAL grads (CBA active businesses); Greenhouse UAL grads + Southwark/Lambeth/Lewisham; Launch CCW grads",
    ageElig: "UAL graduate pathways",
    requirements: "CBA: active business; Greenhouse: impact/digital/physical",
    funding: "CBA bursary £6k; Greenhouse free; Launch free",
    cohort: "CBA ~10",
    focus: "Creative / impact enterprise",
    duration: "CBA ~6 months; Greenhouse 6 months; Launch 6 weeks",
    alumni: "UAL enterprise alumni",
    howIn: "arts.ac.uk careers / Camberwell pages",
    contact: "UAL Student Careers / college KE",
    equity: "0%",
    timing: "CBA deadline often spring; Greenhouse apps ~Oct–Dec; Launch confirm cycle",
    url: "https://www.arts.ac.uk/students/student-careers/awards-funding-and-support/creative-business-accelerator",
    caveats: "UAL Launch is 6 weeks — not 9",
    tags: ["student", "alumni", "social", "non-dilutive"],
  },
  {
    name: "LBS Incubator / Launchpad",
    section: "C",
    type: "Selective incubator + open pre-accelerator",
    forWho: "Incubator: LBS graduating year/alumni full-time; Launchpad: open to non-LBS",
    ageElig: "LBS for incubator",
    requirements: "Full-time on venture (incubator)",
    funding: "Incubator ~£250k in-kind; Launchpad Demo Day prizes up to £18k (2026)",
    cohort: "Incubator ~11/year; Launchpad open",
    focus: "MBA/alumni ventures",
    duration: "Incubator ~10–12 months; Launchpad ~16 weeks",
    alumni: "~150+ companies / £200m+ claimed",
    howIn: "london.edu IEPC; lbslaunchpad.com",
    contact: "LBS IEPC",
    equity: "In-kind free of charge (incubator); Launchpad prizes non-equity",
    timing: "Academic year cycles",
    url: "https://www.lbslaunchpad.com/",
    caveats: "Prefer ~150+/£200m+ not older 160+",
    tags: ["student", "alumni", "mvp", "non-dilutive"],
  },
  {
    name: "InnovationRCA",
    section: "C",
    type: "Incubator + pre-seed",
    forWho: "RCA graduating students, grads, staff",
    ageElig: "RCA affiliation",
    requirements: "Design/innovation ventures",
    funding: "Design & Innovation Fund access; mentoring; Battersea space",
    cohort: "UNKNOWN annual",
    focus: "Design-led startups",
    duration: "Annual programme cycle",
    alumni: "70+ startups; £100m+ raised claims",
    howIn: "innovation@rca.ac.uk",
    contact: "innovation@rca.ac.uk",
    equity: "Yes — 'very small share' depending on investment/market",
    timing: "Annual; 2025/26 apps closed historically Jun",
    url: "https://www.rca.ac.uk/business/innovationrca/our-services/start-programme/",
    caveats: "Exact equity % UNKNOWN",
    tags: ["student", "alumni", "mvp", "equity"],
  },
  {
    name: "Birkbeck Pioneer",
    section: "C",
    type: "Hybrid entrepreneurship programme",
    forWho: "Birkbeck students",
    ageElig: "Students",
    requirements: "Programme phases Nov–Jun",
    funding: "UNKNOWN current year",
    cohort: "UNKNOWN",
    focus: "Awareness → skills → pitch",
    duration: "Nov–Jun (3 phases)",
    alumni: "UNKNOWN",
    howIn: "bbk.ac.uk careers enterprise",
    contact: "Enterprise team (email on page)",
    equity: "UNKNOWN / support",
    timing: "2026–27 details summer 2026",
    url: "https://www.bbk.ac.uk/student-services/careers-and-enterprise/start-a-business",
    caveats: "Funding/contact thin on page",
    tags: ["student", "pre-idea", "non-dilutive"],
  },
  {
    name: "SOAS Student Enterprise",
    section: "C",
    type: "Pre-accelerator + accelerator",
    forWho: "SOAS students",
    ageElig: "Students",
    requirements: "Idea or established student business",
    funding: "Competitions — amounts UNKNOWN publicly",
    cohort: "UNKNOWN",
    focus: "Student enterprise; social enterprise course partners",
    duration: "Pre-accel ~6 weeks; accel for established",
    alumni: "UNKNOWN",
    howIn: "SOAS Enterprise office",
    contact: "SOAS Enterprise",
    equity: "UNKNOWN",
    timing: "Confirm cycle",
    url: "https://www.soas.ac.uk/research/enterprise/student-enterprise",
    caveats: "Thin public metrics",
    tags: ["student", "social", "pre-idea"],
  },
  {
    name: "Goldsmiths NX / SYNAPSE",
    section: "C",
    type: "Creative enterprise hub + workshops",
    forWho: "Goldsmiths students/grads; NX with Lewisham/GLA",
    ageElig: "Goldsmiths community",
    requirements: "Scheme invitation for some offers",
    funding: "Cash metrics UNKNOWN",
    cohort: "Student Entrepreneurship Scheme ~up to 3 cos/year",
    focus: "Creative/cultural entrepreneurship",
    duration: "Workshops + EiR rolling",
    alumni: "UNKNOWN",
    howIn: "enterprise@gold.ac.uk",
    contact: "enterprise@gold.ac.uk",
    equity: "UNKNOWN",
    timing: "Rolling EiR; workshops calendar",
    url: "https://www.gold.ac.uk/nxhub/",
    caveats: "Thin cash metrics",
    tags: ["student", "alumni", "social"],
  },
  {
    name: "Brunel Entrepreneur Hub",
    section: "C",
    type: "Hub + incubators + competitions",
    forWho: "Students & alumni ≤3 years",
    ageElig: "≤3y alumni",
    requirements: "Consultations / incubator readiness",
    funding: "Venture Competition share of £10k; Freelancer Awards ≤£5k; IPSE up to 10 places",
    cohort: "IPSE 10/yr",
    focus: "Venture + freelance",
    duration: "Self-paced incubators; IPSE 12 months",
    alumni: "UNKNOWN",
    howIn: "hub@brunel.ac.uk",
    contact: "hub@brunel.ac.uk; 01895 807570",
    equity: "No equity ask found",
    timing: "Venture Comp entries historically to 6 Feb 2026",
    url: "https://www.brunel.ac.uk/student-professional-development/entrepreneur-hub/support",
    caveats: "",
    tags: ["student", "alumni", "pre-idea", "mvp", "non-dilutive"],
  },
  {
    name: "Kingston Nest / Bright Ideas / Fast Track",
    section: "C",
    type: "Incubation community + competitions",
    forWho: "Kingston students/grads",
    ageElig: "Kingston community",
    requirements: "Pathway Nest via Fast Track etc.",
    funding: "Nest pitch up to £10k seed (pages); Bright Ideas prizes historically ~£1k",
    cohort: "Fast Track ~25 (2026 LinkedIn)",
    focus: "Student enterprise",
    duration: "Fast Track ~Jul–Oct 2026; Nest up to ~24 months (some pages)",
    alumni: "Strong HE-BCI graduate startup rankings",
    howIn: "entrepreneurship@kingston.ac.uk",
    contact: "entrepreneurship@kingston.ac.uk",
    equity: "Confirm on £10k seed terms",
    timing: "Fast Track 6 Jul–13 Oct 2026 (LinkedIn)",
    url: "https://www.kingston.ac.uk/enterprise-education/",
    caveats: "Stipend claims UNKNOWN/verify",
    tags: ["student", "alumni", "pre-idea", "mvp"],
  },
  {
    name: "Middlesex EDH / MDXcelerator",
    section: "C",
    type: "Enterprise hub + accelerator workshops",
    forWho: "Students, alumni, staff",
    ageElig: "MDX community",
    requirements: "Workshops/pitching",
    funding: "Santander-sponsored prizes (e.g. £3k international 2024)",
    cohort: "UNKNOWN 2025/26 London",
    focus: "Student start-ups",
    duration: "Workshop series",
    alumni: "UNKNOWN",
    howIn: "edh@mdx.ac.uk",
    contact: "edh@mdx.ac.uk; Williams Building",
    equity: "Prizes non-equity",
    timing: "2025/26 London intake partly UNKNOWN",
    url: "https://unihub.mdx.ac.uk/employment/your-enterprise",
    caveats: "London 2025/26 terms thin",
    tags: ["student", "alumni", "pre-idea", "non-dilutive"],
  },
  {
    name: "Westminster Zone29",
    section: "C",
    type: "Staged grants + support",
    forWho: "Students + grads ≤3 years",
    ageElig: "≤3y grads",
    requirements: "Progress Explore→Ideate→Validate→Activate",
    funding: "Ideate £500; Validate £2,500; Activate ≤£5,000; Ignite ≤£1,500",
    cohort: "N/A staged",
    focus: "Start or grow a business",
    duration: "Stage-based",
    alumni: "UNKNOWN",
    howIn: "westminster.ac.uk/zone29",
    contact: "Zone29 / WeNetwork",
    equity: "0% grants",
    timing: "Ongoing",
    url: "https://www.westminster.ac.uk/zone29/students/start-or-grow-a-business",
    caveats: "Ignite is broader student fund",
    tags: ["student", "alumni", "pre-idea", "mvp", "non-dilutive"],
  },
  {
    name: "Greenwich Generator",
    section: "C",
    type: "Enterprise hub at Cooper Powerhouse",
    forWho: "Students + alumni ≤2 years; community summer accel",
    ageElig: "≤2y alumni for some",
    requirements: "Enterprise Challenge streams",
    funding: "Generator Bursaries ≤£1,250 (Santander)",
    cohort: "UNKNOWN",
    focus: "Social/commercial/freelance",
    duration: "Bootcamps + summer accelerator",
    alumni: "UNKNOWN",
    howIn: "gre.ac.uk/business/generator",
    contact: "Generator / Cooper Powerhouse",
    equity: "0%",
    timing: "Enterprise Challenge reopen Oct 2026",
    url: "https://www.gre.ac.uk/business/generator",
    caveats: "",
    tags: ["student", "alumni", "social", "non-dilutive"],
  },
  {
    name: "LSBU South Bank Works",
    section: "C",
    type: "Year-long incubator",
    forWho: "Freelancers/charities/companies; LSBU community + open framing",
    ageElig: "UNKNOWN",
    requirements: "Validate/build/grow sprints",
    funding: "FREE support",
    cohort: "UNKNOWN",
    focus: "Local enterprise",
    duration: "Year-long",
    alumni: "UNKNOWN",
    howIn: "starters@lsbu.ac.uk",
    contact: "Mohammed Ali; starters@lsbu.ac.uk",
    equity: "0%",
    timing: "Ongoing",
    url: "https://www.lsbu.ac.uk/business/entrepreneurship/southbank-starters/south-bank-works",
    caveats: "",
    tags: ["student", "alumni", "social", "mvp", "non-dilutive"],
  },
  {
    name: "UEL RDSBL Enterprise",
    section: "C",
    type: "Enterprise / incubator support",
    forWho: "UEL students/grads",
    ageElig: "UEL community",
    requirements: "Confirm current offer on UEL pages",
    funding: "UNKNOWN current amounts",
    cohort: "UNKNOWN",
    focus: "Student enterprise",
    duration: "UNKNOWN",
    alumni: "UNKNOWN",
    howIn: "UEL enterprise / RDSBL",
    contact: "UEL Enterprise",
    equity: "UNKNOWN",
    timing: "Confirm",
    url: "https://www.uel.ac.uk/",
    caveats: "Thin public detail — verify before applying",
    tags: ["student", "alumni"],
  },
  {
    name: "London Met Big Idea / Summer Startup",
    section: "C",
    type: "Competition + 8-week programme",
    forWho: "Students & recent grads",
    ageElig: "Students/recent grads",
    requirements: "Pitch categories Commercial/Creative/Social/Freelance",
    funding: "Cash + support; Founders Fund ≤£200 from £3k pot (HOME ≤3y)",
    cohort: "UNKNOWN",
    focus: "Ideas → summer validation",
    duration: "Summer Startup 8 weeks",
    alumni: "Pathway to Holloway hot-desking",
    howIn: "bigideachallenge.co.uk",
    contact: "London Met Enterprise",
    equity: "0%",
    timing: "Big Idea 2026 deadline cited 1 Feb",
    url: "https://bigideachallenge.co.uk/",
    caveats: "",
    tags: ["student", "alumni", "pre-idea", "social", "non-dilutive"],
  },
  {
    name: "Ravensbourne StartUp Lab / SEEDS",
    section: "C",
    type: "Creative startup support",
    forWho: "Ravensbourne students/grads",
    ageElig: "Ravensbourne community",
    requirements: "Creative enterprise fit",
    funding: "UNKNOWN exact 2026",
    cohort: "UNKNOWN",
    focus: "Creative/digital enterprise",
    duration: "UNKNOWN",
    alumni: "UNKNOWN",
    howIn: "Ravensbourne enterprise pages",
    contact: "Ravensbourne Enterprise",
    equity: "UNKNOWN",
    timing: "Confirm",
    url: "https://www.ravensbourne.ac.uk/",
    caveats: "Thin public detail",
    tags: ["student", "alumni"],
  },
  {
    name: "London Demo Day",
    section: "C",
    type: "Cross-uni showcase",
    forWho: "Selected startups from UCL/LSE/King's/Imperial/QMUL",
    ageElig: "Via partner uni programmes",
    requirements: "Selected ~4 startups/uni",
    funding: "Showcase (not a grant programme)",
    cohort: "~20 startups",
    focus: "Investor demo day",
    duration: "Event",
    alumni: "Partner uni ventures",
    howIn: "Via home university entrepreneurship teams",
    contact: "Partner QUEST/Enterprise Labs",
    equity: "N/A",
    timing: "9 Sep 2026 @ Imperial",
    url: "https://www.qmul.ac.uk/quest/programmes-and-events/london-demo-day/",
    caveats: "",
    tags: ["student", "alumni", "mvp"],
  },
  {
    name: "Venture Crawl",
    section: "C",
    type: "Cross-London founder crawl / network",
    forWho: "Students via partner unis (~13+ London partners)",
    ageElig: "Student participants",
    requirements: "Via home uni",
    funding: "None / networking",
    cohort: "Event-based",
    focus: "Ecosystem exposure",
    duration: "Crawl event(s)",
    alumni: "N/A",
    howIn: "Home university EI teams (e.g. King's)",
    contact: "Partner EI offices",
    equity: "0%",
    timing: "Confirm annual dates",
    url: "https://www.kcl.ac.uk/entrepreneurship",
    caveats: "Not a funding programme",
    tags: ["student", "pre-idea"],
  },
  {
    name: "MedTech SuperConnector",
    section: "C",
    type: "ECR MedTech commercialisation",
    forWho: "UK early-career researchers in MedTech",
    ageElig: "ECR",
    requirements: "Track-based; Imperial-led historically multi-partner",
    funding: "Current standard amount UNKNOWN (legacy ≤£45k dated)",
    cohort: "UNKNOWN current",
    focus: "MedTech translation",
    duration: "6 months",
    alumni: "MSC alumni network",
    howIn: "medtechsuperconnector.com",
    contact: "MSC programme",
    equity: "Typically support/grant framing — confirm",
    timing: "Confirm open tracks",
    url: "https://medtechsuperconnector.com/programme/",
    caveats: "Funding figures dated — verify current track",
    tags: ["research spinout", "non-dilutive"],
  },
  {
    name: "Capital Enterprise (operator)",
    section: "D",
    type: "Network + programme delivery org",
    forWho: "Ecosystem orgs + founders via programmes",
    ageElig: "N/A",
    requirements: "Programme-dependent",
    funding: "Programme-dependent (typically free to founders)",
    cohort: "N/A operator",
    focus: "Diversity, medtech, readiness programmes",
    duration: "N/A",
    alumni: "Via Amplify/Ascend/Cancer Tech etc.",
    howIn: "capitalenterprise.org",
    contact: "Capital Enterprise",
    equity: "Programmes typically 0%",
    timing: "Ongoing",
    url: "https://capitalenterprise.org/",
    caveats: "Operator — canonical CE entry; don't double-count as separate accel",
    tags: ["mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "Grow London Local / Global / Early Stage",
    section: "D",
    type: "GLA / L&P support stack",
    forWho: "London SMEs/scaleups; Pre-Global for underrepresented",
    ageElig: "UNKNOWN",
    requirements: "London-based; stage-specific",
    funding: "Free support (no equity cheque)",
    cohort: "Global: 260 scaleups past 12 mo (Mar 2026 GLA)",
    focus: "Local discovery; export; early growth",
    duration: "Global 12 months; Local on-demand",
    alumni: "Monzo, Revolut, Bloom & Wild, Brompton (GLA-stated)",
    howIn: "growlondonlocal.london; grow.london",
    contact: "London & Partners",
    equity: "0%",
    timing: "Cohort-based Global; Local rolling",
    url: "https://www.growlondonlocal.london/",
    caveats: "UKSPF-backed — time-boxed funding risk after Mar 2026 spend cliff",
    tags: ["scaleup", "mvp", "non-dilutive"],
  },
  {
    name: "Amplify Venture",
    section: "D",
    type: "Diversity scale support (UKSPF)",
    forWho: "Ambitious London founders, esp. underrepresented",
    ageElig: "UNKNOWN",
    requirements: "London trading ≥18 months; ≥£50k revenue; ≥2 staff (verify current)",
    funding: "Free support; cash UNKNOWN",
    cohort: "GLA target 150 businesses",
    focus: "Scale; diversity",
    duration: "Bootcamp + modules (2025 cycle through ~Feb 2026)",
    alumni: "UNKNOWN",
    howIn: "amplifyventure.org",
    contact: "Capital Enterprise / OneTech / Foundervine",
    equity: "0%",
    timing: "Register interest; UKSPF cliff risk",
    url: "https://www.amplifyventure.org/",
    caveats: "Prefer GLA target 150 (not older 120); UKSPF time-boxed",
    tags: ["scaleup", "non-dilutive"],
  },
  {
    name: "Ascend",
    section: "D",
    type: "Investment readiness (women/non-binary)",
    forWho: "London growth-stage women/non-binary-led",
    ageElig: "UNKNOWN",
    requirements: "Revenue; growing customers; fundraising intent",
    funding: "Support / intros — not cash grant advertised",
    cohort: "Target ~35 (CE); Foundervine 2025: 25; 227+ apps for 35",
    focus: "Investment readiness",
    duration: "~8–12 weeks",
    alumni: "Aggregate raises (GLA)",
    howIn: "Capital Enterprise / Foundervine EOI",
    contact: "CE; Foundervine",
    equity: "0% (UKSPF)",
    timing: "Future cohort via EOI; UKSPF cliff",
    url: "https://capitalenterprise.org/ascend/",
    caveats: "UKSPF time-boxed",
    tags: ["scaleup", "mvp", "non-dilutive"],
  },
  {
    name: "Investment Ready (Diverse Founders)",
    section: "D",
    type: "Investment-readiness course",
    forWho: "London pre-seed/seed diverse founders",
    ageElig: "UNKNOWN",
    requirements: "32 boroughs; UK Ltd; MVP; fundraising in 6–9 months",
    funding: "Support + referrals (not a cheque)",
    cohort: "214 businesses / 182 diverse founders aggregate impact stats",
    focus: "Fundraising readiness",
    duration: "Prefer 6 weeks (Funding London) vs 8 Grow listing conflict",
    alumni: "£32.1m raised aggregate claim",
    howIn: "Funding London / Grow London Local",
    contact: "Funding London; Mountside Ventures",
    equity: "0%",
    timing: "Cohort-based; UKSPF cliff",
    url: "https://fundinglondon.co.uk/programmes",
    caveats: "Duration conflict 6 vs 8 — prefer Funding London 6 weeks",
    tags: ["mvp", "non-dilutive"],
  },
  {
    name: "UnLtd Awards",
    section: "D",
    type: "Nonprofit grants + support",
    forWho: "Social entrepreneurs; Funding Futures 16–30 marginalised",
    ageElig: "16+ (Millennium); 16–30 Funding Futures",
    requirements: "Right to live/work UK; venture <4 years if incorporated",
    funding: "Starting Up ≤£8k; Scaling Up ≤£18k",
    cohort: "Often ~650 apps; 150 awards 2023/24",
    focus: "Social entrepreneurship",
    duration: "~12 months support",
    alumni: "UnLtd winners pages",
    howIn: "Eligibility checker → portal",
    contact: "awardapplications@unltd.org.uk",
    equity: "0% grant",
    timing: "Round closes 31 Aug 2026 10:00; results mid-Dec",
    url: "https://unltd.org.uk/awards/",
    caveats: "",
    tags: ["social", "youth", "pre-idea", "mvp", "non-dilutive"],
  },
  {
    name: "SSE Growth & Resilience + Shifting",
    section: "D",
    type: "Social enterprise learning + Match Trading",
    forWho: "Charities/CICs/community businesses",
    ageElig: "Org-focused",
    requirements: "G&R: London; 3+ yrs; <20% trading income; £50k+ income",
    funding: "G&R up to £19k; Shifting Start Up ≤£3k / Trade Up ≤£7k Match Trading",
    cohort: "G&R 60 places / 3 cohorts; Shifting 80 graduated Jan 2025",
    focus: "Trading income / resilience",
    duration: "G&R 18 months (Apr 2026–Sep 2027); Shifting 12 months",
    alumni: "UNKNOWN",
    howIn: "the-sse.org",
    contact: "School for Social Entrepreneurs",
    equity: "Grants non-equity (repayable grant debt-like)",
    timing: "G&R active; Shifting UKSPF time-boxed",
    url: "https://www.the-sse.org/learning-support/programmes/",
    caveats: "Shifting UKSPF cliff; G&R City Bridge funded",
    tags: ["social", "non-dilutive"],
  },
  {
    name: "TERN Changemakers",
    section: "D",
    type: "Refugee social enterprise incubator",
    forWho: "Refugees / refugee-background early social entrepreneurs",
    ageElig: "UNKNOWN",
    requirements: "Refugee background; UK; idea piloted preferred",
    funding: "Grants facilitated (not fixed per founder); alumni >£200k facilitated claim",
    cohort: "UNKNOWN",
    focus: "Social enterprise",
    duration: "6 months",
    alumni: "TERN impact counters",
    howIn: "wearetern.org",
    contact: "TERN CIC",
    equity: "0%",
    timing: "Watch next cycle (2026 apps closed Dec 2025)",
    url: "https://wearetern.org/",
    caveats: "",
    tags: ["social", "pre-idea", "non-dilutive"],
  },
  {
    name: "Impact Hub Together for Wellbeing",
    section: "D",
    type: "Social enterprise incubator",
    forWho: "Greater London SEs ≤5 years; preventative mental health",
    ageElig: "UNKNOWN",
    requirements: "Registered SE; London; wellbeing focus",
    funding: "Cash UNKNOWN",
    cohort: "7 participants",
    focus: "Preventative mental wellbeing",
    duration: "6 months; ~4 hrs/month",
    alumni: "UNKNOWN",
    howIn: "Impact Hub London programmes",
    contact: "Impact Hub London",
    equity: "UNKNOWN — confirm",
    timing: "2026 apps closed; waitlist",
    url: "https://london.impacthub.net/programmes/together-for-wellbeing-programme-2026",
    caveats: "Equity/cash UNKNOWN",
    tags: ["social", "non-dilutive"],
  },
  {
    name: "ICURe",
    section: "D",
    type: "Academic pre-accelerator",
    forWho: "Researchers & technicians at UK unis / eligible orgs",
    ageElig: "Researcher career stage",
    requirements: "Research commercialisation team",
    funding: "Discover ≤£2.5k; Explore ≤£35k",
    cohort: "National delivery partners",
    focus: "Market validation → spinout/licence",
    duration: "Discover: part-time 8–11 wks OR 3-wk Sprint; Explore 12–16 wks FT",
    alumni: "UK spinout pipeline",
    howIn: "iuk-business-connect.org.uk/icure",
    contact: "IUK Business Connect",
    equity: "0% grant",
    timing: "Rolling cohorts 2026–27",
    url: "https://iuk-business-connect.org.uk/programme/icure/",
    caveats: "Canonical ICURe; Discover both formats ≤£2.5k",
    tags: ["research spinout", "non-dilutive"],
  },
  {
    name: "CyberASAP",
    section: "D",
    type: "Academic cyber accelerator",
    forWho: "UK academic cyber research teams",
    ageElig: "Academic institutions",
    requirements: "Cyber research → startup path",
    funding: "Phase grants (Y10 Phase 1 share of up to £800k competition)",
    cohort: "170+ teams; 42 companies claim",
    focus: "Cyber security spinouts",
    duration: "~10–11 months",
    alumni: "Programme claims £47m further funding",
    howIn: "IUK Business Connect CyberASAP",
    contact: "IUK Business Connect",
    equity: "0% grant",
    timing: "Annual cycle; Y10 Phase 1 closed Feb 2026",
    url: "https://iuk-business-connect.org.uk/programme/cyberasap/",
    caveats: "",
    tags: ["research spinout", "non-dilutive"],
  },
  {
    name: "Innovate UK Venture Builder Pilot",
    section: "D",
    type: "Grant + venture builder for deep-tech spinouts",
    forWho: "UK MSME spinouts ≤24 months (or incorporate by deadline)",
    ageElig: "Company ≤24 months",
    requirements: "Industrial Strategy tech; ≤£100k prior investor funding",
    funding: "Up to £150k grant",
    cohort: "UNKNOWN",
    focus: "AI, eng bio, advanced materials",
    duration: "~9 months (to 30 Jun 2027)",
    alumni: "UNKNOWN",
    howIn: "Innovation Funding Service",
    contact: "UKRI / IFS",
    equity: "0% grant",
    timing: "EOI closed 22 May 2026 — watch future rounds",
    url: "https://www.ukri.org/opportunity/innovate-uk-venture-builder-pilot-expression-of-interest/",
    caveats: "",
    tags: ["research spinout", "non-dilutive"],
  },
  {
    name: "Empower100 (Virgin StartUp)",
    section: "D",
    type: "Investment-readiness accelerator (UKSPF)",
    forWho: "Greater London women; BAME; disability founders",
    ageElig: "UNKNOWN",
    requirements: "Trading ≥18 months; ≥2 employees; ≥£50k turnover",
    funding: "Free; no equity stated",
    cohort: "Designed ~100; site 'Founders Supported: 120'",
    focus: "Investment readiness for diverse founders",
    duration: "Conflict: FAQ 8 weeks vs promo 7 weeks",
    alumni: "UNKNOWN",
    howIn: "virginstartup.org/empower-100 waiting list",
    contact: "Virgin StartUp programme lead",
    equity: "0%",
    timing: "Current cohort closed; UKSPF cliff",
    url: "https://www.virginstartup.org/empower-100/",
    caveats: "Duration 7 vs 8 conflict; UKSPF time-boxed",
    tags: ["mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "Power Up London (Big Issue Invest)",
    section: "D",
    type: "Social investment / growth support",
    forWho: "London social enterprises / impact orgs (confirm current criteria)",
    ageElig: "UNKNOWN",
    requirements: "Confirm on Big Issue Invest pages",
    funding: "Confirm current offer — may be investment not grant",
    cohort: "UNKNOWN",
    focus: "Social impact growth",
    duration: "UNKNOWN",
    alumni: "UNKNOWN",
    howIn: "bigissue.com/invest",
    contact: "Big Issue Invest",
    equity: "Confirm (investment vehicle)",
    timing: "Confirm open window",
    url: "https://www.bigissue.com/invest/power-up-london/",
    caveats: "Verify live terms — some pages thin",
    tags: ["social"],
  },
  {
    name: "GoodTech Ventures",
    section: "D",
    type: "Impact / good-tech ventures programme",
    forWho: "Impact-driven innovators (Catch22 / GoodTech)",
    ageElig: "UNKNOWN",
    requirements: "Confirm cohort criteria",
    funding: "UNKNOWN exact",
    cohort: "Cohort 3 publicised",
    focus: "Impact-driven tech",
    duration: "UNKNOWN",
    alumni: "Cohort announcements",
    howIn: "goodtech.ventures / Catch22",
    contact: "GoodTech / Catch22",
    equity: "UNKNOWN",
    timing: "Confirm next cohort",
    url: "https://www.catch-22.org.uk/find-services/goodtech-ventures/",
    caveats: "Confirm current recruitment",
    tags: ["social", "mvp"],
  },
  {
    name: "Game Changer / Games London Accelerator",
    section: "D",
    type: "Games industry programmes (Film London)",
    forWho: "UK game studio founders",
    ageElig: "UNKNOWN",
    requirements: "Studio / IP focus (Accelerator: Unlocking IP)",
    funding: "Accelerator free; up to 5 studios",
    cohort: "Accelerator up to 5",
    focus: "Games / IP",
    duration: "Accelerator 8 weeks (Jan–Mar 2026 cycle)",
    alumni: "UNKNOWN",
    howIn: "games.london",
    contact: "Film London / Games London",
    equity: "0% stated for Accelerator",
    timing: "2026 Accelerator apps closed Dec 2025",
    url: "https://games.london/accelerator/",
    caveats: "Game Changer distinct from Games London Accelerator",
    tags: ["mvp", "non-dilutive"],
  },
  {
    name: "CRL (Central Research Laboratory)",
    section: "D",
    type: "Hardware / deeptech accelerator space",
    forWho: "Hardware / deeptech startups (Plus X / CRL)",
    ageElig: "UNKNOWN",
    requirements: "Confirm CRL accelerator cohort criteria",
    funding: "Confirm current",
    cohort: "CRL Accelerator numbering continues (e.g. 14)",
    focus: "Hardware commercialisation",
    duration: "Confirm",
    alumni: "UNKNOWN",
    howIn: "plusxinnovation.com CRL pages",
    contact: "Plus X / CRL",
    equity: "Confirm",
    timing: "Confirm",
    url: "https://www.plusxinnovation.com/programmes/crl-accelerator-14",
    caveats: "Verify live cohort terms",
    tags: ["mvp", "research spinout"],
  },
  {
    name: "Open London (Newable)",
    section: "D",
    type: "London business support / openness programme",
    forWho: "London SMEs (confirm criteria)",
    ageElig: "UNKNOWN",
    requirements: "Confirm application form vs blog status",
    funding: "UNKNOWN",
    cohort: "UNKNOWN",
    focus: "Business growth / openness",
    duration: "UNKNOWN",
    alumni: "UNKNOWN",
    howIn: "Newable Open London",
    contact: "Newable",
    equity: "UNKNOWN",
    timing: "Status conflict blog vs form — verify",
    url: "https://www.newable.co.uk/",
    caveats: "Application status conflict — verify before relying",
    tags: ["mvp", "scaleup"],
  },
  {
    name: "SHIFT Future Industries Demonstrator",
    section: "D",
    type: "LLDC future industries demonstrator",
    forWho: "Future industries / LLDC ecosystem innovators",
    ageElig: "UNKNOWN",
    requirements: "Confirm SHIFT criteria",
    funding: "UNKNOWN",
    cohort: "UNKNOWN",
    focus: "Future industries / East London",
    duration: "UNKNOWN",
    alumni: "UNKNOWN",
    howIn: "shiftlondon.co.uk",
    contact: "SHIFT / LLDC",
    equity: "UNKNOWN",
    timing: "Confirm",
    url: "https://shiftlondon.co.uk/future-industries-demonstrator/",
    caveats: "Verify live offer",
    tags: ["mvp", "climate"],
  },
  {
    name: "Just Transition (Startup Discovery School)",
    section: "D",
    type: "Climate justice incubator/accelerator (UKSPF)",
    forWho: "Climate-themed startups; Camden/Islington/Lambeth focus",
    ageElig: "UNKNOWN",
    requirements: "Confirm tracks",
    funding: "Incubator pitch prizes ≤£3.5k; Accelerator £5k grant (SDS also 'up to £7.5k')",
    cohort: "GLA ~100 startups across programme types",
    focus: "Just transition / climate",
    duration: "Incubator 12 wks; Accelerator 6 months",
    alumni: "UNKNOWN",
    howIn: "startupdiscoveryschool.com",
    contact: "Startup Discovery School",
    equity: "0% grants",
    timing: "Marked CLOSED; original window to Mar 2025 — continuity UNKNOWN",
    url: "https://startupdiscoveryschool.com/programmes/just-transition",
    caveats: "UKSPF time-boxed / likely ended for original window",
    tags: ["climate", "social", "non-dilutive"],
  },
  {
    name: "Barts HealthTech SME Support",
    section: "D",
    type: "NHS-readiness support (not classic accel)",
    forWho: "HealthTech/life sciences SMEs registered or active in London",
    ageElig: "N/A",
    requirements: "London active SME",
    funding: "Support / pilots / grant navigation — not fixed cheque",
    cohort: "Aim ≤200 SMEs; 156 engaged reported",
    focus: "NHS navigation for HealthTech",
    duration: "2-year UKSPF project",
    alumni: "UNKNOWN",
    howIn: "healthtech@bartslifesciences.org",
    contact: "healthtech@bartslifesciences.org",
    equity: "0%",
    timing: "Round 2 launching; UKSPF time-boxed",
    url: "https://bartslifesciences.org/delivery/healthtech/",
    caveats: "UKSPF cliff",
    tags: ["mvp", "scaleup", "non-dilutive"],
  },
  {
    name: "Southwark Impact Growth Studio",
    section: "D",
    type: "Growth-stage social impact + grants",
    forWho: "Impact orgs with strong Southwark ties; underrepresented-led",
    ageElig: "UNKNOWN",
    requirements: "UK registered; Southwark ties",
    funding: "Milestone grants £10k–£25k",
    cohort: "30 spaces (2026 accelerator block)",
    focus: "Social impact growth",
    duration: "18-month studio frame; also 10-week accelerator block",
    alumni: "UNKNOWN",
    howIn: "foundervine.com Southwark Impact Growth Studio",
    contact: "Foundervine; Southwark Council LAP",
    equity: "0% grant",
    timing: "2026 window listed; confirm",
    url: "https://www.foundervine.com/our-programmes/southwark-impact-growth-studio",
    caveats: "Grants £10k–£25k; duration framing 18-mo vs 10-wk block",
    tags: ["social", "scaleup", "non-dilutive"],
  },
  {
    name: "King's Trust Enterprise",
    section: "D",
    type: "Youth enterprise grants/loans + support",
    forWho: "Ages 18–30 starting out",
    ageElig: "18–30",
    requirements: "Right to work UK; ≥50% ownership; start-up funding path rules",
    funding: "Test idea ≤£500; Start Up Grant £100–£5k; loan £500–£25k; combined access up to ~£30k (not guaranteed)",
    cohort: "Delivery-based",
    focus: "Youth enterprise",
    duration: "Workshops → planning → 2–3 yrs mentoring",
    alumni: "UNKNOWN",
    howIn: "kingstrust.org.uk / GOV.UK listing",
    contact: "King's Trust London",
    equity: "0% on grants; loans repayable",
    timing: "Rolling via local office",
    url: "https://www.gov.uk/business-finance-support/enterprise-programme-for-young-people-uk",
    caveats: "Formerly Prince's Trust",
    tags: ["youth", "pre-idea", "non-dilutive"],
  },
  {
    name: "Start Up Loans / Virgin StartUp",
    section: "D",
    type: "Gov-backed personal loan + mentoring",
    forWho: "18+; UK resident; right to work; trading <60 months (from 6 Apr 2026)",
    ageElig: "18+",
    requirements: "Unable to secure other finance; UK business",
    funding: "£500–£25k/founder (up to £100k/business); 7.5% interest from 6 Apr 2026",
    cohort: "N/A loan product",
    focus: "Debt finance for startups",
    duration: "1–5 year term",
    alumni: "National SUL portfolio",
    howIn: "virginstartup.org / startuploans.co.uk",
    contact: "Virgin StartUp (delivery partner)",
    equity: "Debt, not equity",
    timing: "Rolling",
    url: "https://www.virginstartup.org/start-up-loans/",
    caveats: "",
    tags: ["pre-idea", "mvp", "youth", "non-dilutive"],
  },
  {
    name: "Evo Pioneers (Trampery)",
    section: "D",
    type: "Borough workspace incubator",
    forWho: "Aspiring entrepreneurs in Hackney/Haringey/Southwark",
    ageElig: "UNKNOWN",
    requirements: "Local connection to boroughs",
    funding: "6 months free desk + 6 months reduced",
    cohort: "Old Street 12; Tottenham 4; Peckham 8",
    focus: "Local early founders/creatives",
    duration: "12 months",
    alumni: "UNKNOWN",
    howIn: "thetrampery.com Evo Pioneers",
    contact: "The Trampery",
    equity: "0%",
    timing: "Apps 15 Jun–15 Aug 2026; start ~14 Sep 2026",
    url: "https://thetrampery.com/evolearning/training-for-entrepreneurs/evo-pioneers/",
    caveats: "",
    tags: ["pre-idea", "youth", "non-dilutive"],
  },
  {
    name: "DigitalHealth.London Accelerator",
    section: "D",
    type: "NHS scaling accelerator",
    forWho: "Digital health SMEs scaling into NHS",
    ageElig: "N/A company",
    requirements: "SME; NHS scaling fit",
    funding: "Support; free; UKSPF part-funded",
    cohort: "17 recently; alumni 177 companies",
    focus: "Digital health NHS adoption",
    duration: "12 months",
    alumni: "177 companies",
    howIn: "digitalhealth.london",
    contact: "HIN South London / MedCity partners",
    equity: "0%",
    timing: "Apps currently closed at research",
    url: "https://digitalhealth.london/programmes/accelerator",
    caveats: "UKSPF part-funded — cliff risk",
    tags: ["scaleup", "mvp", "non-dilutive"],
  },
  {
    name: "LIHE MedTech Venture Kickstarter",
    section: "D",
    type: "MedTech accelerator pathway to BMC",
    forWho: "UK cos commercialising medical devices (incl SaMD); TRL≥4",
    ageElig: "N/A",
    requirements: "≥1 day/week in-person at LIHE London",
    funding: "Programme free; pathway to closed BMC feasibility",
    cohort: "UNKNOWN",
    focus: "MedTech",
    duration: "~4 months",
    alumni: "UNKNOWN",
    howIn: "lihe.org.uk",
    contact: "LIHE",
    equity: "0%",
    timing: "Recent cycle Nov 2025–Feb 2026",
    url: "https://lihe.org.uk/innovate-uk-biomedical-catalyst-medtech-venture-kickstarter",
    caveats: "Canonical LIHE public entry alongside King's MedTech",
    tags: ["research spinout", "mvp", "non-dilutive"],
  },
  {
    name: "Google Campus London",
    section: "E",
    type: "DEAD campus",
    forWho: "N/A",
    ageElig: "N/A",
    requirements: "Do not apply",
    funding: "N/A",
    cohort: "N/A",
    focus: "Was Shoreditch campus",
    duration: "Closed 2021",
    alumni: "Historical Campus companies",
    howIn: "N/A — permanently closed",
    contact: "N/A",
    equity: "N/A",
    timing: "DEAD 2021",
    url: "https://startup.google.com/programs/accelerator/",
    caveats: "Permanently closed 2021; use Google for Startups programmes instead",
    tags: [],
  },
  {
    name: "WeWork Labs",
    section: "E",
    type: "DEAD incubator brand",
    forWho: "N/A",
    ageElig: "N/A",
    requirements: "Do not apply",
    funding: "N/A",
    cohort: "N/A",
    focus: "Was Labs incubation",
    duration: "Shut 30 Jun 2022 globally (ex India JV)",
    alumni: "Historical",
    howIn: "N/A",
    contact: "N/A",
    equity: "N/A",
    timing: "DEAD 2022",
    url: "https://www.wework.com/",
    caveats: "WeWork London coworking ≠ Labs incubator",
    tags: [],
  },
  {
    name: "LCIF (London Co-Investment Fund)",
    section: "E",
    type: "Deployed fund — not open",
    forWho: "Historical London science/digital/tech",
    ageElig: "N/A",
    requirements: "N/A",
    funding: "£85m fund fully deployed by Mar 2019",
    cohort: "N/A",
    focus: "Was co-investment",
    duration: "Closed",
    alumni: "Historical portfolio",
    howIn: "Do not treat as open programme",
    contact: "Funding London historical",
    equity: "Was equity co-invest",
    timing: "Deployed 2019",
    url: "https://www.london.gov.uk/programmes-strategies/shaping-local-places/funding-opportunities/london-co-investment-fund-lcif",
    caveats: "Capital fully deployed — not open",
    tags: [],
  },
  {
    name: "Young Academy (Young Foundation)",
    section: "E",
    type: "Closed to new investment",
    forWho: "N/A",
    ageElig: "N/A",
    requirements: "N/A",
    funding: "N/A",
    cohort: "70+ ventures 2014–2020 historical",
    focus: "Was education venture accel",
    duration: "Closed",
    alumni: "Historical",
    howIn: "Do not apply",
    contact: "N/A",
    equity: "N/A",
    timing: "Closed to new investments",
    url: "https://www.youngfoundation.org/the-young-academy/",
    caveats: "DEAD for new founders; Practice-Builders is different",
    tags: [],
  },
  {
    name: "Collider",
    section: "E",
    type: "Paused new investing",
    forWho: "N/A",
    ageElig: "N/A",
    requirements: "N/A",
    funding: "N/A",
    cohort: "N/A",
    focus: "Was media/tech investor-accelerator",
    duration: "Paused",
    alumni: "Historical",
    howIn: "Do not expect new investing",
    contact: "N/A",
    equity: "N/A",
    timing: "Paused new investing",
    url: "https://www.collider.vc/",
    caveats: "Paused new investing",
    tags: [],
  },
  {
    name: "Startupbootcamp London FinTech",
    section: "E",
    type: "Not active London FinTech cohort",
    forWho: "N/A",
    ageElig: "N/A",
    requirements: "N/A",
    funding: "N/A",
    cohort: "N/A",
    focus: "Was FinTech accel",
    duration: "Not active",
    alumni: "Historical",
    howIn: "Do not assume London FinTech cohort",
    contact: "N/A",
    equity: "N/A",
    timing: "Not active",
    url: "https://www.startupbootcamp.org/",
    caveats: "Entity may still be registered; no clear active London FinTech cohort",
    tags: [],
  },
  {
    name: "SETsquared",
    section: "E",
    type: "Not London",
    forWho: "Bath/Bristol/Cardiff/Exeter/Southampton/Surrey unis",
    ageElig: "N/A",
    requirements: "N/A",
    funding: "N/A",
    cohort: "N/A",
    focus: "Regional university enterprise",
    duration: "N/A",
    alumni: "Regional",
    howIn: "setsquared.co.uk — not a London scheme",
    contact: "N/A",
    equity: "N/A",
    timing: "N/A",
    url: "https://www.setsquared.co.uk/",
    caveats: "NOT London — common confusion",
    tags: [],
  },
  {
    name: "LSE GAP",
    section: "E",
    type: "Defunct (replaced by Fellowship)",
    forWho: "N/A",
    ageElig: "N/A",
    requirements: "N/A",
    funding: "N/A",
    cohort: "Was ≤10/year",
    focus: "Was Generate Accelerator",
    duration: "Operated 2020–2025",
    alumni: "Historical GAP",
    howIn: "Use LSE Generate Fellowship instead",
    contact: "generate@lse.ac.uk",
    equity: "Was 0%",
    timing: "Defunct 2026+",
    url: "https://info.lse.ac.uk/staff/divisions/research-and-innovation/generate/Generate-Accelerator-Programme",
    caveats: "Replaced by Fellowship from 2026",
    tags: [],
  },
  {
    name: "Mayor's Entrepreneur Competition",
    section: "E",
    type: "Revamping / not open",
    forWho: "Was London students",
    ageElig: "Students historically",
    requirements: "N/A",
    funding: "Historical prizes £560k+ awarded",
    cohort: "Historical 35 winners",
    focus: "Student ideas for London",
    duration: "Paused",
    alumni: "28 still running claim",
    howIn: "Not open while revamping",
    contact: "Mayor's Fund for London",
    equity: "Was prizes",
    timing: "Revamping — seeking funding",
    url: "https://www.mayorsfundforlondon.org.uk/employability-skills/mayors-entrepreneur-competition/",
    caveats: "Not open",
    tags: [],
  }
];
